version: '3.8'

services:
  tennis-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
